/**
 * /robots.txt — generated by Next.js App Router.
 * --------------------------------------------------------------
 * Allows all crawlers and points them at the sitemap.
 */
import type { MetadataRoute } from "next";
import { client } from "./lib/sanity/client";
import { siteSettingsQuery } from "./lib/sanity/queries";
import { withFallback } from "./lib/sanity/fallbacks";
import { siteSettingsFallback } from "./lib/sanity/fallbacks";

export default async function robots(): Promise<MetadataRoute.Robots> {
  const site = await client.fetch(siteSettingsQuery);
  const s = withFallback(site, siteSettingsFallback);
  const origin = (s.siteUrl ?? "https://www.wewakeindigreen.com").replace(
    /\/$/,
    ""
  );

  return {
    rules: [{ userAgent: "*", allow: "/" }],
    sitemap: `${origin}/sitemap.xml`,
    host: origin,
  };
}
