/**
 * /sitemap.xml — generated by Next.js App Router.
 * --------------------------------------------------------------
 * Lists the homepage + /blog index + every published blog post.
 * Slugs come from Sanity so the sitemap auto-updates as editors
 * publish new posts.
 */
import type { MetadataRoute } from "next";
import { client } from "./lib/sanity/client";
import {
  blogsQuery,
  siteSettingsQuery,
} from "./lib/sanity/queries";
import {
  siteSettingsFallback,
  withFallback,
} from "./lib/sanity/fallbacks";

type BlogStub = {
  slug?: { current?: string };
  publishedAt?: string;
};

export default async function sitemap(): Promise<MetadataRoute.Sitemap> {
  // Pull settings (for the canonical origin) + blog list together.
  const [site, blogs] = await Promise.all([
    client.fetch(siteSettingsQuery),
    client.fetch<BlogStub[]>(blogsQuery),
  ]);

  const s = withFallback(site, siteSettingsFallback);
  const origin = (s.siteUrl ?? "https://www.wewakeindigreen.com").replace(
    /\/$/,
    ""
  );

  // Static pages first.
  const now = new Date();
  const entries: MetadataRoute.Sitemap = [
    {
      url: `${origin}/`,
      lastModified: now,
      changeFrequency: "weekly",
      priority: 1.0,
    },
    {
      url: `${origin}/blog`,
      lastModified: now,
      changeFrequency: "weekly",
      priority: 0.8,
    },
  ];

  // One entry per blog post that has a usable slug.
  for (const b of blogs ?? []) {
    const slug = b?.slug?.current;
    if (!slug) continue;
    const pubDate = b?.publishedAt ? new Date(b.publishedAt) : now;
    entries.push({
      url: `${origin}/blog/${slug}`,
      lastModified: Number.isNaN(pubDate.getTime()) ? now : pubDate,
      changeFrequency: "monthly",
      priority: 0.6,
    });
  }

  return entries;
}
